// <auto-generated />
using System;
using FinApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinApp.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinApp.Data.Entities.FinancialReleaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("FinancialRelease");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua dos Canários, 123",
                            Amount = 40000m,
                            CNPJ = "15098917000148",
                            City = "Curitiba",
                            Discount = 20000m,
                            District = "Centro",
                            DueDate = new DateTime(2023, 5, 9, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8790),
                            Name = "EMPRESA XYP",
                            Number = "ID 9932931",
                            OperationId = 1,
                            Phone = "47 9998-74566",
                            ReleaseDate = new DateTime(2023, 4, 9, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8776),
                            State = "PR",
                            ZipCode = "89295-024"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rua dos Canários, 123",
                            Amount = 40000m,
                            CNPJ = "15098917000148",
                            City = "Curitiba",
                            Discount = 20000m,
                            District = "Centro",
                            DueDate = new DateTime(2023, 6, 8, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8820),
                            Name = "EMPRESA XYP",
                            Number = "ID 9932931",
                            OperationId = 1,
                            Phone = "47 9998-74566",
                            ReleaseDate = new DateTime(2023, 5, 9, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8818),
                            State = "PR",
                            ZipCode = "89295-024"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua dos Canários, 123",
                            Amount = 40000m,
                            CNPJ = "15098917000148",
                            City = "Curitiba",
                            Discount = 20000m,
                            District = "Centro",
                            DueDate = new DateTime(2023, 7, 8, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8833),
                            Name = "EMPRESA XYP",
                            Number = "ID 9932931",
                            OperationId = 1,
                            Phone = "47 9998-74566",
                            ReleaseDate = new DateTime(2023, 6, 8, 17, 9, 58, 361, DateTimeKind.Local).AddTicks(8832),
                            State = "PR",
                            ZipCode = "89295-024"
                        });
                });

            modelBuilder.Entity("FinApp.Data.Entities.OperationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "EMPRESA XYP",
                            Status = "Enviando"
                        });
                });

            modelBuilder.Entity("FinApp.Data.Entities.FinancialReleaseEntity", b =>
                {
                    b.HasOne("FinApp.Data.Entities.OperationEntity", "Operations")
                        .WithMany("FinancialRelease")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("FinApp.Data.Entities.OperationEntity", b =>
                {
                    b.Navigation("FinancialRelease");
                });
#pragma warning restore 612, 618
        }
    }
}
