version: '3.4'

services:
  finapp.api:
    image: ${DOCKER_REGISTRY-}finappapi
    build:
      context: .
      dockerfile: FinApp.API/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

  app:
    extends:
      file: ../../../FinApp/FinApp.Front/FinApp/docker-compose.yml
      service: finapp.front

  database:
    image: mysql:8.0.22
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: finapp
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: FinApp
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  db-volume:

